spring.application.name=chatapi
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_ISSUER_URI:http://127.0.0.1:9000}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWK_SET_URI:http://localhost:9000/oauth2/jwks}
server.port=${SERVER_PORT:8081}

spring.grpc.client.default-channel.address=${GRPC_SERVER_ADDRESS:localhost:8083}
spring.grpc.client.default-channel.secure=false
