spring.application.name=bff

spring.security.oauth2.client.provider.authservice.issuer-uri=${AUTH_ISSUER_URI:http://auth.localtest.me}
spring.security.oauth2.client.registration.authservice.client-id=gateway-client
spring.security.oauth2.client.registration.authservice.client-secret=secret
spring.security.oauth2.client.registration.authservice.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.authservice.redirect-uri=${AUTH_REDIRECT_URI:http://bff.localtest.me/login/oauth2/code/authservice}
spring.security.oauth2.client.registration.authservice.scope=user.read,openid

# Interna endpoints (containrar emellan) - Måste vara explicita om issuer-uri är den publika
spring.security.oauth2.client.provider.authservice.authorization-uri=http://auth.localtest.me/oauth2/authorize
spring.security.oauth2.client.provider.authservice.token-uri=http://authservice:9000/oauth2/token
spring.security.oauth2.client.provider.authservice.jwk-set-uri=http://authservice:9000/oauth2/jwks
spring.security.oauth2.client.provider.authservice.user-info-uri=http://authservice:9000/userinfo
spring.security.oauth2.client.provider.authservice.user-name-attribute=sub


spring.graphql.graphiql.enabled=true
spring.cloud.refresh.enabled=false
